/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 20 15:59:12 CEST 2016
 */

package es.uca.webservices.analisis.design;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.fail;

import java.awt.HeadlessException;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class Main_ESTest extends Main_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[20];
      // Undeclared exception!
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: HeadlessException");
      
      } catch(HeadlessException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.awt.GraphicsEnvironment", e);
      }
  }
}
