/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Aug 20 13:15:22 CEST 2016
 */

package es.uca.webservices.analisis;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;

@EvoSuiteClassExclude
public class BPELActivityAnalyzer_ESTest_scaffolding {

  @org.junit.Rule 
  public org.junit.rules.Timeout globalTimeout = new org.junit.rules.Timeout(4000); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "es.uca.webservices.analisis.BPELActivityAnalyzer"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 


  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(BPELActivityAnalyzer_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.xmlbeans.xml.stream.XMLInputStream",
      "org.apache.xmlbeans.SchemaAnnotation",
      "org.apache.xmlbeans.impl.regex.Token$ConditionToken",
      "org.apache.xmlbeans.impl.schema.SchemaTypeSystemImpl",
      "org.apache.xmlbeans.impl.store.Saaj$SaajCallback",
      "org.apache.xmlbeans.impl.regex.RegexParser",
      "org.apache.xmlbeans.QNameSet",
      "org.apache.xmlbeans.SchemaProperty",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.ProcessDocument$Factory",
      "org.apache.xmlbeans.SchemaType",
      "org.apache.xmlbeans.impl.soap.Text",
      "org.apache.xmlbeans.impl.regex.ParserForXMLSchema",
      "org.apache.xmlbeans.impl.store.DomImpl$SaajCdataNode",
      "org.apache.xmlbeans.impl.regex.Token$StringToken",
      "org.apache.xmlbeans.SchemaGlobalElement$Ref",
      "org.apache.xmlbeans.XmlTokenSource",
      "org.apache.xmlbeans.impl.schema.BuiltinSchemaTypeSystem",
      "org.apache.xmlbeans.impl.schema.SchemaTypeSystemCompiler",
      "org.apache.xmlbeans.SchemaModelGroup",
      "org.apache.xmlbeans.impl.values.TypeStoreUser",
      "org.apache.xmlbeans.XmlDocumentProperties",
      "es.uca.webservices.analisis.BPELActivityAnalyzer",
      "org.apache.xmlbeans.impl.values.XmlValueDisconnectedException",
      "org.apache.xmlbeans.impl.regex.Op$CharOp",
      "org.apache.xmlbeans.SchemaAnnotated",
      "org.apache.xmlbeans.impl.values.XmlIntegerImpl",
      "org.apache.xmlbeans.Filer",
      "org.apache.xmlbeans.impl.regex.Op$RangeOp",
      "org.apache.xmlbeans.impl.store.DomImpl$TextNode",
      "org.apache.xmlbeans.impl.values.XmlStringImpl",
      "org.apache.xmlbeans.impl.store.DomImpl$Dom",
      "org.apache.xmlbeans.impl.store.Path",
      "org.apache.xmlbeans.impl.store.Cur$CurLoadContext",
      "org.apache.xmlbeans.impl.store.DomImpl$CdataNode",
      "org.apache.xmlbeans.XmlCursor",
      "org.apache.xmlbeans.impl.regex.Op$ChildOp",
      "org.apache.xmlbeans.impl.regex.Token$ParenToken",
      "org.apache.xmlbeans.SchemaField",
      "org.apache.xmlbeans.impl.store.DomImpl$CharNode",
      "org.apache.xmlbeans.impl.store.Locale$1",
      "org.apache.xmlbeans.SchemaModelGroup$Ref",
      "org.apache.xmlbeans.impl.regex.Token$ConcatToken",
      "org.apache.xmlbeans.impl.store.QNameFactory",
      "org.apache.xmlbeans.xml.stream.utils.NestedThrowable",
      "org.apache.xmlbeans.impl.regex.Token",
      "es.uca.webservices.testgen.api.parsers.ParserException",
      "org.apache.xmlbeans.SchemaComponent",
      "org.apache.xmlbeans.impl.common.XPath$XPathCompileException",
      "org.apache.xmlbeans.impl.common.PrefixResolver",
      "org.apache.xmlbeans.SchemaComponent$1",
      "org.apache.xmlbeans.impl.values.JavaIntegerHolder",
      "org.apache.xmlbeans.XmlBeans$1",
      "org.apache.xmlbeans.SchemaTypeLoader",
      "org.apache.xmlbeans.SchemaGlobalElement",
      "org.apache.xmlbeans.impl.values.JavaStringHolder",
      "org.apache.xmlbeans.impl.schema.FileResourceLoader",
      "org.apache.xmlbeans.SchemaTypeElementSequencer",
      "org.apache.xmlbeans.impl.values.TypeStoreUserFactory",
      "org.apache.xmlbeans.impl.regex.Op$ModifierOp",
      "org.apache.xmlbeans.SchemaComponent$Ref",
      "org.apache.xmlbeans.UserType",
      "org.apache.xmlbeans.impl.regex.SchemaRegularExpression",
      "org.apache.xmlbeans.XmlException",
      "org.apache.xmlbeans.impl.soap.Node",
      "org.apache.xmlbeans.impl.common.ValidationContext",
      "org.apache.xmlbeans.impl.common.SystemCache",
      "org.apache.xmlbeans.impl.store.Path$PathEngine",
      "org.apache.xmlbeans.XmlString",
      "org.apache.xmlbeans.PrePostExtension",
      "org.apache.xmlbeans.InterfaceExtension",
      "org.apache.xmlbeans.impl.store.Locale$LoadContext",
      "org.apache.xmlbeans.impl.schema.XmlValueRef",
      "org.apache.xmlbeans.xml.stream.XMLStreamException",
      "org.apache.xmlbeans.impl.schema.SchemaAttributeModelImpl",
      "org.apache.xmlbeans.impl.regex.RegularExpression",
      "org.apache.xmlbeans.impl.schema.SchemaTypeLoaderImpl",
      "org.apache.xmlbeans.impl.regex.Op$StringOp",
      "org.apache.xmlbeans.impl.values.XmlObjectBase",
      "org.apache.xmlbeans.impl.store.Locale$SaxHandler",
      "org.apache.xmlbeans.impl.common.ValidatorListener",
      "org.apache.xmlbeans.impl.schema.SchemaTypeSystemCompiler$Parameters",
      "org.apache.xmlbeans.SchemaParticle",
      "org.apache.xmlbeans.impl.regex.Token$UnionToken",
      "org.apache.xmlbeans.impl.schema.SchemaTypeImpl",
      "org.apache.xmlbeans.impl.values.NamespaceManager",
      "org.apache.xmlbeans.SchemaAttributeGroup$Ref",
      "org.apache.xmlbeans.XmlAnySimpleType",
      "org.apache.xmlbeans.SchemaLocalAttribute",
      "org.apache.xmlbeans.XmlInteger",
      "org.apache.xmlbeans.XmlSaxHandler",
      "org.apache.xmlbeans.XmlBeans",
      "org.apache.xmlbeans.impl.values.TypeStore",
      "org.apache.xmlbeans.impl.regex.SchemaRegularExpression$1",
      "org.apache.xmlbeans.impl.schema.SchemaTypeLoaderImpl$SchemaTypeLoaderCache",
      "org.apache.xmlbeans.impl.regex.ParseException",
      "es.uca.webservices.analisis.io.BPELWriter",
      "org.apache.xmlbeans.SchemaTypeSystem",
      "org.apache.xmlbeans.impl.common.XmlWhitespace",
      "org.apache.xmlbeans.QNameSetSpecification",
      "org.apache.xmlbeans.impl.values.TypeStoreVisitor",
      "es.uca.webservices.bpel.InvalidProcessException",
      "es.uca.webservices.testgen.autoseed.source.BPELSource",
      "org.apache.xmlbeans.impl.store.Cur",
      "es.uca.webservices.testgen.autoseed.source.XMLSource",
      "org.apache.xmlbeans.XmlRuntimeException",
      "org.apache.xmlbeans.GDateSpecification",
      "org.apache.xmlbeans.SchemaIdentityConstraint$Ref",
      "org.json.simple.JSONStreamAware",
      "org.json.simple.JSONAware",
      "org.apache.xmlbeans.impl.store.Locale$XmlReaderSaxLoader",
      "org.apache.xmlbeans.XmlDecimal",
      "org.apache.xmlbeans.ResourceLoader",
      "org.apache.xmlbeans.impl.regex.Op",
      "org.json.simple.JSONArray",
      "org.apache.xmlbeans.impl.schema.SchemaParticleImpl",
      "org.apache.xmlbeans.impl.regex.Op$UnionOp",
      "org.apache.xmlbeans.impl.regex.REUtil",
      "org.apache.xmlbeans.impl.schema.SchemaTypeLoaderBase",
      "org.apache.xmlbeans.impl.regex.RangeToken",
      "org.apache.xmlbeans.impl.values.XmlValueOutOfRangeException",
      "org.apache.xmlbeans.impl.store.Locale$DocProps",
      "org.apache.xmlbeans.GDurationSpecification",
      "org.apache.xmlbeans.impl.schema.PathResourceLoader",
      "org.apache.xmlbeans.impl.common.XmlLocale",
      "org.apache.xmlbeans.impl.schema.SchemaContainer",
      "org.apache.xmlbeans.impl.values.XmlValueNotSupportedException",
      "org.apache.xmlbeans.SchemaType$Ref",
      "org.apache.xmlbeans.SchemaLocalElement",
      "org.apache.xmlbeans.XmlObject",
      "org.apache.xmlbeans.SimpleValue",
      "org.apache.xmlbeans.SchemaAttributeGroup",
      "org.apache.xmlbeans.impl.store.Locale$SaxLoader",
      "org.apache.xmlbeans.impl.store.Locale$PiccoloSaxLoader",
      "org.apache.xmlbeans.BindingConfig",
      "org.apache.xmlbeans.impl.store.DomImpl$SaajTextNode",
      "org.apache.xmlbeans.impl.regex.Token$ClosureToken",
      "org.apache.xmlbeans.SchemaGlobalAttribute",
      "org.apache.xmlbeans.SchemaGlobalAttribute$Ref",
      "org.apache.xmlbeans.impl.values.XmlValueNotNillableException",
      "org.apache.xmlbeans.XmlOptions",
      "org.apache.xmlbeans.impl.store.Query",
      "org.apache.xmlbeans.impl.store.Locale",
      "org.apache.xmlbeans.impl.common.QNameHelper",
      "org.apache.xmlbeans.SchemaAttributeModel",
      "org.apache.xmlbeans.impl.regex.Op$ConditionOp",
      "org.apache.xmlbeans.impl.regex.Token$CharToken",
      "org.apache.xmlbeans.impl.values.XmlObjectBase$ValueOutOfRangeValidationContext",
      "org.apache.xmlbeans.impl.regex.Token$ModifierToken"
    );
  } 
}
