/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 20 13:16:17 CEST 2016
 */

package es.uca.webservices.analisis;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class BPTSAnalyzer_ESTest extends BPTSAnalyzer_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      BPTSAnalyzer bPTSAnalyzer0 = null;
      try {
        bPTSAnalyzer0 = new BPTSAnalyzer((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("es.uca.webservices.analisis.BPTSAnalyzer", e);
      }
  }

  @Test
  public void test1()  throws Throwable  {
      BPTSAnalyzer bPTSAnalyzer0 = new BPTSAnalyzer("BPTS File not found.");
      String string0 = bPTSAnalyzer0.readNodes();
      assertEquals("BPTS File not found.", string0);
  }

  @Test
  public void test2()  throws Throwable  {
      BPTSAnalyzer bPTSAnalyzer0 = new BPTSAnalyzer(".bpts");
      // Undeclared exception!
      try { 
        bPTSAnalyzer0.readNodes();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.io.FileNotFoundException: /home/kevin/workspace/anal-bpel-4mmt-final/.bpts (No existe el archivo o el directorio)
         //
         assertThrownBy("es.uca.webservices.analisis.BPTSAnalyzer", e);
      }
  }

  @Test
  public void test3()  throws Throwable  {
      BPTSAnalyzer bPTSAnalyzer0 = new BPTSAnalyzer("BPTS File not found.");
      String string0 = bPTSAnalyzer0.getJSONoutput();
      assertEquals("/home/kevin/metamorphic/json/null_testCases.json", string0);
  }
}
