/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 20 15:55:31 CEST 2016
 */

package es.uca.webservices.analisis.match;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class ReportMatcher_ESTest extends ReportMatcher_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      ReportMatcher reportMatcher0 = null;
      try {
        reportMatcher0 = new ReportMatcher((String) null, "XDCd==d6U<!omr");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.io.File", e);
      }
  }
}
