/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Aug 20 13:24:57 CEST 2016
 */

package es.uca.webservices.analisis.io;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;

@EvoSuiteClassExclude
public class BPELReader_ESTest_scaffolding {

  @org.junit.Rule 
  public org.junit.rules.Timeout globalTimeout = new org.junit.rules.Timeout(4000); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "es.uca.webservices.analisis.io.BPELReader"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 


  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(BPELReader_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.xmlbeans.xml.stream.XMLInputStream",
      "org.apache.xmlbeans.impl.values.XmlObjectBase",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TFlow",
      "org.apache.xmlbeans.impl.common.ValidatorListener",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TTargets",
      "org.apache.xmlbeans.XmlQName",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TEmpty",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.impl.TInvokeImpl",
      "org.apache.xmlbeans.QNameSet",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TExtensibleElements",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TExtensionActivity",
      "org.apache.xmlbeans.GDuration",
      "org.apache.xmlbeans.SchemaProperty",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TIf",
      "org.apache.xmlbeans.impl.values.NamespaceManager",
      "org.apache.xmlbeans.SchemaType",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TAssign",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.impl.TActivityImpl",
      "org.apache.xmlbeans.XmlAnySimpleType",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TElseif",
      "org.apache.xmlbeans.XmlTokenSource",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TValidate",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TTo",
      "org.apache.xmlbeans.impl.values.TypeStore",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TSources",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TWhile",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TActivity",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.BPELVariableNames",
      "org.apache.xmlbeans.impl.values.TypeStoreUser",
      "org.apache.xmlbeans.XmlDocumentProperties",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TCatch",
      "es.uca.webservices.analisis.io.BPELWriter",
      "org.apache.xmlbeans.impl.values.XmlValueDisconnectedException",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TScope",
      "es.uca.webservices.analisis.io.BPELReader",
      "org.apache.xmlbeans.SchemaAnnotated",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.impl.TVariableImpl",
      "org.apache.xmlbeans.impl.values.TypeStoreVisitor",
      "org.apache.xmlbeans.QNameSetSpecification",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TReply",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.impl.TExtensibleElementsImpl",
      "org.apache.xmlbeans.XmlRuntimeException",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TWait",
      "org.apache.xmlbeans.GDateSpecification",
      "org.apache.xmlbeans.XmlCursor",
      "org.json.simple.JSONStreamAware",
      "org.json.simple.JSONAware",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TForEach",
      "org.apache.xmlbeans.SchemaField",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TCopy",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TExpression",
      "org.json.simple.JSONArray",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TFromParts",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.BPELVariableName",
      "org.apache.xmlbeans.XmlNCName",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TBooleanExpr",
      "org.apache.xmlbeans.impl.values.XmlValueOutOfRangeException",
      "org.apache.xmlbeans.GDurationSpecification",
      "org.apache.xmlbeans.impl.values.XmlValueNotSupportedException",
      "org.apache.xmlbeans.impl.common.XmlLocale",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TThrow",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TVariable",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TReceive",
      "org.apache.xmlbeans.SchemaComponent",
      "org.apache.xmlbeans.XmlObject",
      "org.apache.xmlbeans.XmlNormalizedString",
      "org.apache.xmlbeans.SimpleValue",
      "org.apache.xmlbeans.impl.values.XmlComplexContentImpl",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TBoolean$Enum",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.impl.TIfImpl",
      "org.apache.xmlbeans.impl.common.PrefixResolver",
      "org.apache.xmlbeans.XmlName",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TCorrelationsWithPattern",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TSequence",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TRepeatUntil",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TDocumentation",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TCompensateScope",
      "org.apache.xmlbeans.impl.values.XmlValueNotNillableException",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TExit",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TInvoke",
      "org.apache.xmlbeans.XmlException",
      "org.apache.xmlbeans.impl.common.ValidationContext",
      "org.apache.xmlbeans.XmlOptions",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TToParts",
      "org.apache.xmlbeans.XmlToken",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TRethrow",
      "org.apache.xmlbeans.XmlString",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TFrom",
      "org.apache.xmlbeans.GDate",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TBoolean",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.impl.TValidateImpl",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TCompensate",
      "org.apache.xmlbeans.StringEnumAbstractBase",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TActivityContainer",
      "org.oasisOpen.docs.wsbpel.x20.process.executable.TPick",
      "org.apache.xmlbeans.impl.values.XmlObjectBase$ValueOutOfRangeValidationContext"
    );
  } 
}
