/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 20 13:24:57 CEST 2016
 */

package es.uca.webservices.analisis.io;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.fail;

import org.apache.xmlbeans.SchemaType;
import org.apache.xmlbeans.impl.values.XmlValueDisconnectedException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.oasisOpen.docs.wsbpel.x20.process.executable.TActivity;
import org.oasisOpen.docs.wsbpel.x20.process.executable.TVariable;
import org.oasisOpen.docs.wsbpel.x20.process.executable.impl.TIfImpl;
import org.oasisOpen.docs.wsbpel.x20.process.executable.impl.TInvokeImpl;
import org.oasisOpen.docs.wsbpel.x20.process.executable.impl.TValidateImpl;
import org.oasisOpen.docs.wsbpel.x20.process.executable.impl.TVariableImpl;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class BPELReader_ESTest extends BPELReader_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      BPELWriter bPELWriter0 = new BPELWriter("");
      BPELReader bPELReader0 = new BPELReader(bPELWriter0);
      TVariableImpl tVariableImpl0 = new TVariableImpl((SchemaType) null);
      // Undeclared exception!
      try { 
        bPELReader0.read((TVariable) tVariableImpl0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.oasisOpen.docs.wsbpel.x20.process.executable.impl.TVariableImpl", e);
      }
  }

  @Test
  public void test1()  throws Throwable  {
      TInvokeImpl tInvokeImpl0 = new TInvokeImpl((SchemaType) null);
      tInvokeImpl0.disconnect_store();
      BPELWriter bPELWriter0 = new BPELWriter("6dhx}");
      BPELReader bPELReader0 = new BPELReader(bPELWriter0);
      // Undeclared exception!
      try { 
        bPELReader0.read((TActivity) tInvokeImpl0);
        fail("Expecting exception: XmlValueDisconnectedException");
      
      } catch(XmlValueDisconnectedException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.apache.xmlbeans.impl.values.XmlObjectBase", e);
      }
  }

  @Test
  public void test2()  throws Throwable  {
      BPELWriter bPELWriter0 = new BPELWriter("");
      BPELReader bPELReader0 = new BPELReader(bPELWriter0);
      TValidateImpl tValidateImpl0 = new TValidateImpl((SchemaType) null);
      bPELReader0.read((TActivity) tValidateImpl0);
      assertFalse(tValidateImpl0.isImmutable());
  }

  @Test
  public void test3()  throws Throwable  {
      TIfImpl tIfImpl0 = new TIfImpl((SchemaType) null);
      BPELReader bPELReader0 = new BPELReader((BPELWriter) null);
      // Undeclared exception!
      try { 
        bPELReader0.read((TActivity) tIfImpl0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.oasisOpen.docs.wsbpel.x20.process.executable.impl.TActivityImpl", e);
      }
  }

  @Test
  public void test4()  throws Throwable  {
      BPELReader bPELReader0 = new BPELReader((BPELWriter) null);
      // Undeclared exception!
      try { 
        bPELReader0.read((TVariable) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("es.uca.webservices.analisis.io.BPELReader", e);
      }
  }
}
